insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('31','1104670800','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('32','1136120400','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('33','1167570000','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('34','1106658000','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('35','1138194000','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('36','1169730000','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('37','1111669200','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('38','1144936800','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('39','1175781600','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('40','1111755600','Easter Saturday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('41','1145023200','Easter Saturday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('42','1175868000','Easter Saturday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('43','1111932000','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('44','1145196000','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('45','1176040800','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('46','1114351200','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('47','1145887200','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('48','1177423200','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('49','1118584800','Queens Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('50','1150034400','Queens Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('51','1181484000','Queens Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('52','1128261600','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('53','1159711200','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('54','1191160800','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('55','1135515600','Christmas Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('56','1166965200','Christmas Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('57','1198501200','Christmas Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('58','1135602000','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('59','1167051600','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('60','1198587600','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('61','1111323600','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('62','1142773200','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('63','1174222800','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('236','1199106000','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('242','1194267600','Family & Community Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('245','1201438800','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('253','1209045600','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('261','1230123600','Christmas Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('269','1212933600','Queen\'s Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('277','1223211600','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('286','1230210000','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('293','1206018000','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('301','1206277200','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('309','1230728400','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('317','1232888400','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('325','1240754400','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('333','1261659600','Christmas Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('341','1244383200','Queen\'s Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('349','1254661200','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('358','1261918800','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('365','1239285600','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('373','1239544800','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('386','1198414800','Christmas Eve','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('391','1205067600','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('403','1236517200','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('407','1264424400','Australia Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('416','1272204000','Anzac Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('417','1293454800','Boxing Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('425','1293368400','Christmas','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('433','1270389600','Easter Monday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('441','1270126800','Good Friday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('450','1286110800','Labour Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('455','1267966800','Canberra Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('456','1276437600','Queen\'s Birthday','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('468','1257166800','Family & Community Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('472','1262264400','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('474','1293800400','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('475','1325336400','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('476','1356958800','New Year\'s Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('506','1253973600','Family & Community Day','Australia/ACT','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('64','1104676200','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('65','1136125800','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('66','1167575400','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('67','1106663400','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('68','1138199400','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('69','1169735400','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('70','1111674600','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('71','1144938600','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('72','1175783400','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('73','1111761000','Easter Saturday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('74','1145025000','Easter Saturday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('75','1175869800','Easter Saturday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('76','1111933800','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('77','1145197800','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('78','1176042600','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('79','1114353000','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('80','1145889000','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('81','1177425000','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('82','1118586600','Queens Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('83','1150036200','Queens Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('84','1181485800','Queens Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('85','1135521000','Christmas Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('86','1166970600','Christmas Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('87','1198506600','Christmas Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('88','1135607400','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('89','1167057000','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('90','1198593000','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('91','1122820200','Picnic Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('92','1154874600','Picnic Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('93','1186324200','Picnic Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('94','1114957800','May Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('95','1146407400','May Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('96','1178461800','May Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('239','1199111400','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('246','1201444200','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('254','1209047400','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('262','1230129000','Christmas Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('270','1212935400','Queen\'s Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('287','1230215400','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('294','1206023400','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('302','1206282600','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('310','1230733800','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('318','1232893800','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('326','1240583400','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('334','1261665000','Christmas Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('342','1244385000','Queen\'s Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('350','1209911400','Labour Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('359','1261924200','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('366','1239287400','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('374','1239546600','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('383','1198420200','Christmas Eve','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('397','1241361000','May Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('398','1249219800','Picnic Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('399','1280669400','Picnic Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('408','1264429800','Australia Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('418','1293460200','Boxing Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('426','1293373800','Christmas','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('434','1270391400','Easter Monday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('442','1270132200','Good Friday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('457','1276439400','Queen\'s Birthday','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('467','1272810600','May Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('477','1262269800','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('478','1293805800','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('479','1325341800','New Year\'s Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('499','1272205800','Anzac Day','Australia/North','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('1','1104498000','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('2','1136120400','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('3','1167570000','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('4','1106658000','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('5','1138194000','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('6','1169730000','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('7','1111669200','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('8','1144936800','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('9','1175781600','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('10','1111755600','Easter Saturday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('11','1145023200','Easter Saturday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('12','1175868000','Easter Saturday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('13','1111932000','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('14','1145196000','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('15','1176040800','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('16','1114351200','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('17','1145887200','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('18','1177423200','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('19','1118584800','Queens Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('20','1150034400','Queens Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('21','1181484000','Queens Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('22','1128261600','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('23','1159711200','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('24','1191160800','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('25','1135515600','Christmas Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('26','1166965200','Christmas Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('27','1198501200','Christmas Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('28','1135602000','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('29','1167051600','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('30','1198587600','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('235','1199106000','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('240','1189087200','APEC Summit 2007','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('252','1201438800','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('260','1209045600','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('268','1230123600','Christmas Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('276','1212933600','Queen\'s Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('284','1223211600','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('292','1230210000','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('300','1206018000','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('308','1206277200','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('316','1230728400','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('324','1232888400','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('332','1240581600','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('340','1261659600','Christmas Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('348','1244383200','Queen\'s Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('356','1249221600','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('364','1261918800','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('372','1239285600','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('380','1239544800','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('387','1198414800','Christmas Eve','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('404','1254661200','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('409','1264424400','Australia Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('419','1293454800','Boxing Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('427','1293368400','Christmas','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('435','1270389600','Easter Monday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('443','1270126800','Good Friday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('449','1286110800','Labour Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('458','1276437600','Queen\'s Birthday','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('480','1262264400','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('481','1293800400','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('482','1325336400','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('483','1356958800','New Year\'s Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('500','1272204000','Anzac Day','Australia/NSW','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('130','1104672600','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('131','1136122200','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('132','1167571800','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('133','1106659800','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('134','1138195800','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('135','1169731800','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('136','1111671000','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('137','1144938600','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('138','1175783400','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('139','1111757400','Easter Saturday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('140','1145025000','Easter Saturday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('141','1175869800','Easter Saturday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('142','1111933800','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('143','1145197800','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('144','1176042600','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('145','1114353000','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('146','1145889000','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('147','1177425000','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('148','1118586600','Queens Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('149','1150036200','Queens Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('150','1181485800','Queens Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('151','1128263400','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('152','1159713000','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('153','1191162600','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('154','1135517400','Christmas Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('155','1166967000','Christmas Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('156','1198503000','Christmas Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('157','1135603800','Proclamation Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('158','1167053400','Proclamation Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('159','1198589400','Proclamation Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('160','1116167400','Adelaide Cup / Volunteer\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('161','1147444200','Adelaide Cup / Volunteer\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('162','1179671400','Adelaide Cup / Volunteer\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('232','1199107800','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('247','1201440600','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('255','1209047400','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('263','1230125400','Christmas Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('271','1212935400','Queen\'s Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('279','1223213400','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('285','1230211800','Proclamation Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('295','1206019800','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('303','1206279000','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('311','1230730200','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('319','1232890200','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('327','1240583400','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('335','1261661400','Christmas Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('343','1244385000','Queen\'s Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('351','1254663000','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('357','1261920600','Proclamation Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('367','1239287400','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('375','1239546600','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('385','1198416600','Christmas Eve','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('392','1205069400','Adelaide Cup Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('402','1236519000','Adelaide Cup Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('410','1264426200','Australia Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('420','1293456600','Boxing Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('428','1293370200','Christmas','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('436','1270391400','Easter Monday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('444','1270128600','Good Friday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('451','1286112600','Labour Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('459','1276439400','Queen\'s Birthday','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('484','1262266200','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('485','1293802200','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('486','1325338200','New Year\'s Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('498','1236432600','Adelaide Cup Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('501','1272205800','Anzac Day','Australia/South','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('226','1176040800','Easter Monday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('227','1175781600','Good Friday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('228','1177423200','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('229','1145887200','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('230','1114351200','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('231','1198501200','Christmas Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('237','1199106000','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('248','1201438800','Australia Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('256','1209045600','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('264','1230123600','Christmas Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('272','1212933600','Queen\'s Birthday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('280','1205067600','Labour Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('288','1230210000','Boxing Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('296','1206018000','Good Friday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('304','1206277200','Easter Monday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('312','1230728400','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('320','1232888400','Australia Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('328','1240581600','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('336','1261659600','Christmas Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('344','1244383200','Queen\'s Birthday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('352','1236517200','Labour Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('360','1261918800','Boxing Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('368','1239285600','Good Friday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('376','1239544800','Easter Monday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('381','1198587600','Boxing Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('388','1198414800','Christmas Eve','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('390','1202648400','11/02/08','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('411','1264424400','Australia Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('421','1293454800','Boxing Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('429','1293368400','Christmas','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('437','1270389600','Easter Monday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('445','1270126800','Good Friday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('454','1267966800','Eight Hours Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('460','1276437600','Queen\'s Birthday','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('487','1262264400','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('488','1325336400','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('489','1293800400','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('490','1356958800','New Year\'s Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('502','1272204000','Anzac Day','Australia/Tasmania','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('97','1104674400','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('98','1136124000','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('99','1167573600','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('100','1106661600','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('101','1138197600','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('102','1169733600','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('103','1111672800','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('104','1144936800','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('105','1175781600','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('106','1111759200','Easter Saturday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('107','1145023200','Easter Saturday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('108','1175868000','Easter Saturday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('109','1111932000','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('110','1145196000','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('111','1176040800','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('112','1114351200','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('113','1145887200','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('114','1177423200','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('115','1118584800','Queens Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('116','1150034400','Queens Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('117','1181484000','Queens Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('118','1114956000','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('119','1146405600','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('120','1178460000','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('121','1135519200','Christmas Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('122','1166968800','Christmas Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('123','1198504800','Christmas Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('124','1135605600','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('125','1167055200','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('126','1198591200','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('127','1124200800','Royal Queensland Show','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('128','1155650400','Royal Queensland Show','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('129','1187100000','Royal Queensland Show','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('238','1199109600','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('249','1201442400','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('257','1209045600','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('265','1230127200','Christmas Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('273','1212933600','Queen\'s Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('278','1209911400','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('281','1209909600','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('289','1230213600','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('297','1206021600','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('305','1206280800','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('313','1230732000','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('321','1232892000','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('329','1240581600','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('337','1261663200','Christmas Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('345','1244383200','Queen\'s Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('353','1241359200','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('361','1261922400','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('369','1239285600','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('377','1239544800','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('384','1198418400','Christmas Eve','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('400','1249999200','Brisbane Show Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('401','1249999200','Brisbane Show Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('412','1264428000','Australia Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('422','1293458400','Boxing Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('430','1293372000','Christmas','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('438','1270389600','Easter Monday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('446','1270130400','Good Friday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('461','1276437600','Queen\'s Birthday','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('466','1281448800','Brisbane Show Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('491','1262268000','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('492','1293804000','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('493','1325340000','New Year\'s Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('503','1272204000','Anzac Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('505','1272808800','Labour Day','Australia/Queensland','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('163','1104681600','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('164','1136131200','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('165','1167577200','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('166','1106668800','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('167','1138204800','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('168','1169737200','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('169','1111680000','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('170','1144944000','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('171','1175788800','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('172','1111939200','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('173','1145203200','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('174','1176048000','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('175','1114358400','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('176','1145894400','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('177','1177430400','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('178','1127664000','Queens Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('179','1159718400','Queens Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('180','1191168000','Queens Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('181','1110124800','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('182','1141574400','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('183','1173020400','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('184','1135526400','Christmas Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('185','1166972400','Christmas Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('186','1198508400','Christmas Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('187','1135612800','Proclamation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('188','1167058800','Proclamation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('189','1198594800','Proclamation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('190','1117987200','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('191','1149436800','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('192','1180886400','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('233','1199113200','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('250','1201446000','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('258','1209052800','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('266','1230130800','Christmas Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('274','1222617600','Queen\'s Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('282','1204470000','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('290','1230217200','Boxing Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('298','1206025200','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('306','1206284400','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('314','1230735600','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('322','1232895600','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('330','1240761600','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('338','1261670400','Christmas Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('346','1254672000','Queen\'s Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('354','1235919600','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('362','1261929600','Boxing Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('370','1239292800','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('378','1239552000','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('382','1198422000','Christmas Eve','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('393','1212336000','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('395','1241366400','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('396','1243785600','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('405','1254067200','Queen\'s Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('413','1264435200','Australia Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('423','1293465600','Boxing Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('431','1293379200','Christmas','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('439','1270396800','Easter Monday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('447','1270137600','Good Friday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('463','1285516800','Queen\'s Birthday','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('464','1275840000','Foundation Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('494','1262271600','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('495','1293807600','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('496','1325343600','New Year\'s Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('497','1267372800','Labour Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('504','1272211200','Anzac Day','Australia/West','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('193','1104670800','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('194','1136120400','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('195','1167570000','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('196','1106658000','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('197','1138194000','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('198','1169730000','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('199','1111669200','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('200','1144936800','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('201','1175781600','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('202','1111755600','Easter Saturday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('203','1145023200','Easter Saturday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('204','1175868000','Easter Saturday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('205','1111932000','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('206','1145196000','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('207','1176040800','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('208','1114351200','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('209','1145887200','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('210','1177423200','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('211','1118584800','Queens Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('212','1150034400','Queens Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('213','1181484000','Queens Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('214','1110718800','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('215','1142168400','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('216','1173618000','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('217','1135515600','Christmas Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('218','1166965200','Christmas Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('219','1198501200','Christmas Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('220','1135602000','Proclamation Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('221','1167051600','Proclamation Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('222','1198587600','Proclamation Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('223','1130763600','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('224','1162818000','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('225','1194267600','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('234','1199106000','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('241','1194181200','Melbourne Cup Eve','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('251','1201438800','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('259','1209045600','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('267','1230123600','Christmas Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('275','1212933600','Queen\'s Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('283','1205067600','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('291','1230210000','Boxing Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('299','1206018000','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('307','1206277200','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('315','1230728400','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('323','1232888400','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('331','1240581600','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('339','1261659600','Christmas Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('347','1244383200','Queen\'s Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('355','1236517200','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('363','1261918800','Boxing Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('371','1239285600','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('379','1239544800','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('389','1198414800','Christmas Eve','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('394','1225717200','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('406','1257166800','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('414','1264424400','Australia Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('415','1272204000','Anzac Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('424','1293454800','Boxing Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('432','1293368400','Christmas','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('440','1270389600','Easter Monday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('448','1270126800','Good Friday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('452','1267966800','Labour Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('462','1276437600','Queen\'s Birthday','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('465','1288616400','Melbourne Cup Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('469','1262264400','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('470','1293800400','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');
insert into public_holidays (`ph_id`, `ph_date`, `ph_name`, `ph_timezone`, `source_uri`) values('471','1325336400','New Year\'s Day','Australia/Victoria','https://vx.valex.com.au/');

insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (2,'Australian Capital Territory',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (3,'Northern Territory',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (4,'New South Wales',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (5,'South Australia',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (6,'Tasmania',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (7,'Queensland',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (8,'Western Australia',NULL,'');
insert  into `areas`(`area_id`,`area_name`,`polygon_coordinates`,`same_as_uri`) values (9,'Victoria',NULL,'');
